add example and support with OpenAPI 3.2
Allow the CLI to preview and deploy OpenAPI documents
with version 3.2

Add a related example in examples/valid repo,
and dedicated tests.

Error message will change when unexpected version is deployed:

> Error: Unsupported API specification (OpenAPI 4.2.0)
> Please try again with an OpenAPI 2.0, 3.0, 3.1, 3.2 or AsyncAPI 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6 file.

Note/Question:

I don't know how to access to
oas-schemas/schemas/v3.2/schema.json
(do we need to upgrade to dependency?),
so I favored the same schema
'oas-schemas/schemas/v3.2/schema.json'
for now.